/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as QuemSomosIndexRouteImport } from './routes/quem-somos.index'
import { Route as QuemSomosEquipeRouteImport } from './routes/quem-somos.equipe'
import { Route as QuemSomosTransparenciaRouteImport } from './routes/quem-somos.transparencia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosIndexRoute = QuemSomosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuemSomosRoute,
} as any)
const QuemSomosEquipeRoute = QuemSomosEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => QuemSomosRoute,
} as any)
const QuemSomosTransparenciaRoute = QuemSomosTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => QuemSomosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/quem-somos': typeof QuemSomosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
    | '/quem-somos/equipe'
    | '/quem-somos/transparencia'
    | '/quem-somos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/noticias'
    | '/projetos'
    | '/quem-somos/equipe'
    | '/quem-somos/transparencia'
    | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
    | '/quem-somos/equipe'
    | '/quem-somos/transparencia'
    | '/quem-somos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticiasRoute: typeof NoticiasRoute
  ProjetosRoute: typeof ProjetosRoute
  QuemSomosRoute: typeof QuemSomosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/': {
      id: '/quem-somos/'
      path: '/'
      fullPath: '/quem-somos/'
      preLoaderRoute: typeof QuemSomosIndexRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/equipe': {
      id: '/quem-somos/equipe'
      path: '/equipe'
      fullPath: '/quem-somos/equipe'
      preLoaderRoute: typeof QuemSomosEquipeRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/transparencia': {
      id: '/quem-somos/transparencia'
      path: '/transparencia'
      fullPath: '/quem-somos/transparencia'
      preLoaderRoute: typeof QuemSomosTransparenciaRouteImport
      parentRoute: typeof QuemSomosRoute
    }
  }
}

interface QuemSomosRouteChildren {
  QuemSomosEquipeRoute: typeof QuemSomosEquipeRoute
  QuemSomosTransparenciaRoute: typeof QuemSomosTransparenciaRoute
  QuemSomosIndexRoute: typeof QuemSomosIndexRoute
}

const QuemSomosRouteChildren: QuemSomosRouteChildren = {
  QuemSomosEquipeRoute: QuemSomosEquipeRoute,
  QuemSomosTransparenciaRoute: QuemSomosTransparenciaRoute,
  QuemSomosIndexRoute: QuemSomosIndexRoute,
}

const QuemSomosRouteWithChildren = QuemSomosRoute._addFileChildren(
  QuemSomosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticiasRoute: NoticiasRoute,
  ProjetosRoute: ProjetosRoute,
  QuemSomosRoute: QuemSomosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
